export const BUY_PEN = "BUY_PEN"
export const BUY_PENCIL = "BUY_PENCIL"


export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST"
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS"
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE"